export type ProductLevel = 'Beginner' | 'Intermediate' | 'Advanced';
export type ProductCollectionId = 'raspberry-pi-pico' | 'arduino' | 'robotics' | 'ai-vision' | 'raspberry-pi' | 'miscellaneous';

export type ProductCategoryId =
  | 'starter-kits'
  | 'raspberry-pi-pico'
  | 'arduino'
  | 'sensors'
  | 'displays'
  | 'motors'
  | 'breadboards'
  | 'tools'
  | 'power'
  | 'accessories';

export interface AffiliateLinks {
  amazon: string;
  sunfounder: string;
  additionalVendors?: Record<string, string>;
}

export interface KitComponent {
  name: string;
  description: string;
}

export interface KitProject {
  projectId: string;
  title: string;
  description: string;
  difficulty: ProductLevel;
  estimatedTime?: string;
}

export interface KitSalesProfile {
  recommendation: string;
  audienceSummary: string;
  goodFor: string[];
  components: KitComponent[];
  projects: KitProject[];
  sellingPoints: string[];
  documentationUrl: string;
}

export interface PicoKitProfile {
  comparisonLabel: string;
  sectionTitle: string;
  bestFor: string;
  learningFocus: string;
  projectRange: string;
  verifiedProductInfo: string;
  explanation: string;
  selectedComponents?: string[];
  learningAreas: string[];
  projectIds: string[];
  officialProductUrl: string;
  officialDocumentationUrl: string;
}

export interface Product {
  id: string;
  ctaLabel?: string;
  name: string;
  brand: string;
  category: ProductCategoryId;
  shortDescription: string;
  image: {
    src: string;
    alt: string;
  };
  level: ProductLevel;
  platform: string;
  collection?: ProductCollectionId;
  /** Internal affiliate-program note. Never render this value publicly. */
  commissionRateNote?: string;
  featured: boolean;
  tags: string[];
  includedComponents: string[];
  affiliateLinks: AffiliateLinks;
  kitSalesProfile?: KitSalesProfile;
  sellingPoints?: string[];
  highlightedProjects?: string[];
  documentationUrl?: string;
  picoKitProfile?: PicoKitProfile;
}

export interface ProductCategory {
  id: ProductCategoryId;
  name: string;
  description: string;
}

export const affiliatePlaceholders = {
  amazon: 'AFFILIATE_LINK_AMAZON',
  sunfounder: 'AFFILIATE_LINK_SUNFOUNDER',
  sunfounderProductRequired: 'SUNFOUNDER_AFFILIATE_URL_REQUIRED',
} as const;

/** Replace these values only with product-specific links generated by the affiliate dashboard. */
export const sunFounderPicoAffiliateUrls = {
  thales: 'https://www.sunfounder.com/collections/pico-w-pico/products/pico-starter-kit?ref=tmbxfubs',
  euler: 'https://www.sunfounder.com/collections/pico-w-pico/products/sunfounder-euler-kit?ref=tmbxfubs',
  kepler: 'https://www.sunfounder.com/collections/pico-w-pico/products/sunfounder-raspberry-pi-pico-w-ultimate-starter-kit?ref=tmbxfubs',
} as const;

export function isActiveAffiliateLink(url: string): boolean {
  return /^https?:\/\//i.test(url) && !url.startsWith('AFFILIATE_LINK_');
}

export function hasActiveAffiliateLinks(links: AffiliateLinks): boolean {
  return [links.amazon, links.sunfounder, ...Object.values(links.additionalVendors ?? {})]
    .some(isActiveAffiliateLink);
}

export function getProductCtaLabel(product: Product): string {
  if (product.ctaLabel) return product.ctaLabel;
  const shortName = product.name.split(/\s+[–—-]\s+/).at(-1)?.trim() || product.name;
  return `Get the ${shortName} Kit`;
}

export const productCategories: ProductCategory[] = [
  { id: 'starter-kits', name: 'Starter Kits', description: 'All-in-one component collections for a confident first build.' },
  { id: 'raspberry-pi-pico', name: 'Raspberry Pi Pico', description: 'Boards, kits, and accessories for the Pico platform.' },
  { id: 'arduino', name: 'Arduino', description: 'Arduino-compatible boards, shields, and learning kits.' },
  { id: 'sensors', name: 'Sensors', description: 'Modules for measuring light, motion, temperature, distance, and more.' },
  { id: 'displays', name: 'Displays', description: 'LCD, OLED, LED matrix, and indicator display modules.' },
  { id: 'motors', name: 'Motors', description: 'Motors, drivers, servos, and motion-control accessories.' },
  { id: 'breadboards', name: 'Breadboards', description: 'Solderless prototyping boards, jumper wires, and organizers.' },
  { id: 'tools', name: 'Tools', description: 'Meters, cutters, soldering tools, and practical bench essentials.' },
  { id: 'power', name: 'Power', description: 'Safe project power supplies, battery holders, and regulators.' },
  { id: 'accessories', name: 'Accessories', description: 'Useful cables, cases, connectors, and project extras.' },
];

export const products: Product[] = [
  {
    id: 'sunfounder-thales-pico-starter-kit',
    ctaLabel: 'Get the Thales Kit',
    name: 'Raspberry Pi Pico Starter Kit – Thales',
    brand: 'SunFounder',
    category: 'starter-kits',
    shortDescription:
      'This beginner kit contains the core components used in this project and supports additional Raspberry Pi Pico experiments as you continue through the Engineering Maker Lab learning path.',
    image: {
      src: '/product-images/electronics-product.svg',
      alt: 'Generic Engineering Maker Lab illustration representing an electronics starter kit',
    },
    level: 'Beginner',
    platform: 'Raspberry Pi Pico',
    collection: 'raspberry-pi-pico',
    commissionRateNote: '8 percent',
    featured: true,
    tags: ['Raspberry Pi Pico', 'MicroPython', 'Starter Kit'],
    includedComponents: ['Raspberry Pi Pico', 'Breadboard', 'LEDs', 'Resistors', 'Jumper wires', 'Other parts for later beginner projects'],
    affiliateLinks: {
      amazon: affiliatePlaceholders.amazon,
      sunfounder: sunFounderPicoAffiliateUrls.thales,
    },
    kitSalesProfile: {
      recommendation: 'A practical starting point for learning Raspberry Pi Pico programming and basic electronics. The kit combines a Pico board, breadboard components, input devices, and output devices so beginners can complete several progressively more interesting experiments.',
      audienceSummary: 'Complete beginners, students, parents, homeschool families, and makers',
      goodFor: ['Complete beginners', 'Middle and high school students', 'Parents purchasing a STEM kit', 'Homeschool programs', 'Makers learning MicroPython', 'STEM clubs'],
      components: [
        { name: 'Raspberry Pi Pico', description: 'The programmable controller that reads inputs and controls outputs.' },
        { name: 'Breadboard', description: 'Allows circuits to be assembled without soldering.' },
        { name: 'LEDs', description: 'Provide clear visual output for first circuits.' },
        { name: 'Resistors', description: 'Limit current and help protect components.' },
        { name: 'Push buttons', description: 'Introduce digital input and interactive control.' },
        { name: 'RGB LED', description: 'Combines color channels for controllable light experiments.' },
        { name: 'Buzzer', description: 'Adds sound as a programmable output.' },
        { name: 'Potentiometer', description: 'Introduces adjustable analog input.' },
        { name: 'Sensors', description: 'Let projects respond to changes in their surroundings.' },
        { name: 'Jumper wires', description: 'Connect the Pico and components on the breadboard.' },
      ],
      projects: [
        { projectId: 'blink-led', title: 'Blink an LED', description: 'Control a simple output while learning polarity, resistance, and GPIO.', difficulty: 'Beginner', estimatedTime: '20–30 minutes' },
        { projectId: 'push-button-input', title: 'Read a Push Button', description: 'Use a push button as a digital input to control an LED.', difficulty: 'Beginner' },
        { projectId: 'traffic-light', title: 'Traffic Light', description: 'Sequence three LEDs to model a timed traffic signal.', difficulty: 'Beginner' },
        { projectId: 'reaction-game', title: 'Reaction Game', description: 'Combine lights, timing, and player input in an interactive challenge.', difficulty: 'Beginner' },
        { projectId: 'colorful-light', title: 'Colorful Light', description: 'Mix RGB color channels and explore controllable visual output.', difficulty: 'Beginner' },
      ],
      sellingPoints: ['Designed for complete beginners', 'No soldering required for introductory breadboard projects', 'One kit supports multiple experiments', 'Introduces both programming and electronics', 'Projects progress from simple outputs to interactive systems', 'Official SunFounder documentation is available for supported projects'],
      documentationUrl: 'https://docs.sunfounder.com/projects/thales-kit/en/latest/',
    },
    picoKitProfile: {
      comparisonLabel: 'Thales', sectionTitle: 'Thales: Best Simple Starting Point',
      bestFor: 'Complete beginners and lower-cost entry',
      learningFocus: 'Breadboards, LEDs, buttons, basic sensors, and MicroPython fundamentals',
      projectRange: 'A focused beginner path', verifiedProductInfo: '283 items and 18 projects',
      explanation: 'Suitable for complete beginners who want to learn Pico basics without purchasing the largest kit.',
      selectedComponents: ['Raspberry Pi Pico', 'Breadboard', 'LEDs', 'Resistors', 'Push buttons', 'Sound components', 'Basic sensors', 'Jumper wires'],
      learningAreas: ['Blink an LED', 'Read a push button', 'Control RGB LEDs', 'Build a reaction game', 'Learn basic MicroPython'],
      projectIds: ['blink-led', 'push-button-input', 'colorful-light', 'reaction-game'],
      officialProductUrl: 'https://www.sunfounder.com/products/pico-starter-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/thales-kit/en/latest/',
    },
  },
  {
    id: 'sunfounder-euler-pico-ultimate-kit',
    ctaLabel: 'Get the Euler Kit',
    name: 'Raspberry Pi Pico Ultimate Starter Kit – Euler',
    brand: 'SunFounder',
    category: 'starter-kits',
    shortDescription:
      'A beginner-friendly Raspberry Pi Pico kit with a broad component selection for learning circuits, sensors, displays, and physical computing.',
    image: {
      src: '/product-images/sunfounder-pico-ultimate-starter-kit.svg',
      alt: 'Illustration of a Raspberry Pi Pico starter kit and electronic components',
    },
    level: 'Beginner',
    platform: 'Raspberry Pi Pico',
    collection: 'raspberry-pi-pico',
    featured: true,
    tags: ['Raspberry Pi Pico', 'MicroPython', 'Sensors', 'Displays', 'Starter Kit'],
    includedComponents: ['Raspberry Pi Pico with headers', 'Solderless breadboard', 'LEDs', 'Resistor assortment', 'Jumper wires', 'Additional sensors and output components'],
    affiliateLinks: {
      amazon: affiliatePlaceholders.amazon,
      sunfounder: sunFounderPicoAffiliateUrls.euler,
    },
    sellingPoints: ['Broad Pico learning platform', 'Supports electronics and programming practice'],
    highlightedProjects: ['LED and breadboard experiments', 'Sensor projects', 'Display projects'],
    picoKitProfile: {
      comparisonLabel: 'Euler', sectionTitle: 'Euler: Best for More Components and Projects',
      bestFor: 'Beginners who want a larger component collection and a longer project path',
      learningFocus: 'Displays, sounds, drivers, controllers, sensors, and broader electronics applications',
      projectRange: 'A broad, long-form project path', verifiedProductInfo: '320+ components and 113 projects',
      explanation: 'Appropriate for learners who want a broader component collection and significantly more projects without requiring wireless connectivity.',
      selectedComponents: ['Raspberry Pi Pico', 'Displays', 'Sound components', 'Motor drivers', 'Controllers', 'Sensors'],
      learningAreas: ['Displays', 'Motors and drivers', 'Sound', 'Sensors', 'Controllers', 'Larger multi-component projects'],
      projectIds: ['plant-monitor', 'display-experiments', 'motor-control-projects', 'multi-sensor-systems'],
      officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-euler-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/euler-kit/en/latest/',
    },
  },
  {
    id: 'sunfounder-kepler-pico-w-ultimate-kit',
    ctaLabel: 'Get the Kepler Kit',
    name: 'Raspberry Pi Pico W Ultimate Starter Kit – Kepler',
    brand: 'SunFounder', category: 'starter-kits', level: 'Beginner', platform: 'Raspberry Pi Pico W', collection: 'raspberry-pi-pico', featured: false,
    shortDescription: 'A Pico W learning kit for connected electronics, programming, sensors, and interactive hardware experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Pico W electronics kit' },
    tags: ['Raspberry Pi Pico W', 'MicroPython', 'Starter Kit'],
    includedComponents: ['Pico W learning platform', 'Breadboard components', 'Input and output devices'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: sunFounderPicoAffiliateUrls.kepler },
    sellingPoints: ['Adds wireless-capable Pico learning', 'Supports connected and interactive experiments'],
    highlightedProjects: ['Connected electronics', 'Sensor experiments', 'Interactive outputs'],
    picoKitProfile: {
      comparisonLabel: 'Kepler', sectionTitle: 'Kepler: Best for Wireless and IoT',
      bestFor: 'Beginners who want wireless, IoT, and a larger project library',
      learningFocus: 'Sensors, displays, motors, wireless control, and IoT',
      projectRange: 'The largest Pico project library in this comparison', verifiedProductInfo: '450+ components and 117 projects',
      explanation: 'Uses the Raspberry Pi Pico W and suits visitors interested in wireless control, web-connected projects, and IoT.',
      selectedComponents: ['Raspberry Pi Pico W', 'Sensors', 'Displays', 'Motors', 'Pumps', 'Wireless project hardware'],
      learningAreas: ['Wi-Fi', 'IoT', 'Wireless control', 'Sensors', 'Displays', 'Motors and pumps'],
      projectIds: ['digital-bubble-level', 'wireless-control-experiments', 'iot-sensor-monitoring', 'automated-motor-pump-projects'],
      officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-raspberry-pi-pico-w-ultimate-starter-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/kepler-kit/en/latest/',
    },
  },
  {
    id: 'sunfounder-beginners-lab-arduino-uno-r3',
    name: "SunFounder Beginner's Lab Starter Kit with Arduino Uno R3",
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R3', collection: 'arduino', featured: true,
    shortDescription: 'A beginner-oriented Arduino kit for learning circuits, inputs, outputs, and embedded programming.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an Arduino learning kit' },
    tags: ['Arduino', 'Uno R3', 'Starter Kit'], includedComponents: ['Arduino learning platform', 'Breadboard components', 'Sensors and outputs'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Beginner-oriented Arduino platform', 'Combines code with hands-on circuits'], highlightedProjects: ['LED control', 'Sensor input', 'Automation experiments'],
  },
  {
    id: 'sunfounder-elite-explorer-arduino-uno-r4-wifi',
    name: 'SunFounder Elite Explorer Kit with Arduino Uno R4 WiFi',
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R4 WiFi', collection: 'arduino', featured: false,
    shortDescription: 'An Arduino Uno R4 WiFi kit for embedded control, connected experiments, and progressively more capable projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a connected Arduino kit' },
    tags: ['Arduino', 'Uno R4 WiFi', 'Embedded Control'], includedComponents: ['Arduino learning platform', 'Prototyping components', 'Input and output devices'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Modern Arduino platform', 'Supports connected control projects'], highlightedProjects: ['Embedded control', 'Connected sensors', 'Interactive devices'],
  },
  {
    id: 'sunfounder-3-in-1-arduino-uno-r4-minima',
    name: 'SunFounder 3 in 1 Ultimate Starter Kit with Arduino Uno R4 Minima',
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R4 Minima', collection: 'arduino', featured: false,
    shortDescription: 'A broad Arduino Uno R4 Minima starter platform for electronics, sensor, and control experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an Arduino starter platform' },
    tags: ['Arduino', 'Uno R4 Minima', 'Starter Kit'], includedComponents: ['Arduino learning platform', 'Circuit-building components', 'Sensors and outputs'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Supports varied Arduino experiments', 'Builds embedded-control skills'], highlightedProjects: ['Automation', 'Sensor projects', 'Output control'],
  },
  {
    id: 'sunfounder-4wd-robot-car-pico',
    name: 'SunFounder 4WD Robot Car Kit for Raspberry Pi Pico',
    brand: 'SunFounder', category: 'motors', level: 'Beginner', platform: 'Raspberry Pi Pico', collection: 'robotics', featured: true,
    shortDescription: 'A mobile robotics platform for learning motion control, sensing, and programmable robot behavior.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a robot car platform' },
    tags: ['Robotics', 'Raspberry Pi Pico', 'Motion'], includedComponents: ['Mobile robot platform', 'Motion-control hardware', 'Sensors'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Introduces mobile robotics', 'Combines sensing and motion control'], highlightedProjects: ['Obstacle response', 'Programmed movement', 'Sensor-guided driving'],
  },
  {
    id: 'sunfounder-pidog-robot-dog-kit',
    name: 'SunFounder PiDog Robot Dog Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'robotics', featured: false,
    shortDescription: 'A programmable quadruped platform for exploring coordinated motion, sensing, and higher-level robot behaviors.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a quadruped robot' },
    tags: ['Robotics', 'Raspberry Pi', 'Quadruped'], includedComponents: ['Quadruped robot platform', 'Motion hardware', 'Sensors'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Explores coordinated robotic motion', 'Supports behavior programming'], highlightedProjects: ['Walking sequences', 'Responsive behaviors', 'Robot interaction'],
  },
  {
    id: 'sunfounder-galaxyrvr-mars-rover-kit',
    name: 'SunFounder GalaxyRVR Mars Rover Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Arduino', collection: 'robotics', featured: false,
    shortDescription: 'A rover-style robotics platform for navigation, sensing, and programmable mobile-system experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a rover robot' },
    tags: ['Robotics', 'Rover', 'Navigation'], includedComponents: ['Rover platform', 'Drive system', 'Sensors'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Rover-focused mobile robotics', 'Combines navigation and sensing'], highlightedProjects: ['Rover navigation', 'Obstacle response', 'Remote control'],
  },
  {
    id: 'sunfounder-picar-x',
    name: 'SunFounder PiCar-X',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'robotics', featured: false,
    shortDescription: 'A Raspberry Pi robot car platform for programmable movement, sensing, and vision-assisted experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi robot car' },
    tags: ['Robotics', 'Raspberry Pi', 'Vision'], includedComponents: ['Robot car platform', 'Drive and steering hardware', 'Sensors'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Raspberry Pi robotics platform', 'Supports sensing and vision exploration'], highlightedProjects: ['Robot driving', 'Sensor response', 'Vision-assisted behavior'],
  },
  {
    id: 'sunfounder-ai-fusion-lab-kit',
    name: 'SunFounder AI Fusion Lab Kit',
    brand: 'SunFounder', category: 'sensors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'ai-vision', featured: true,
    shortDescription: 'An AI learning platform for experimenting with intelligent inputs, multimodal workflows, and Raspberry Pi projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an AI experiment platform' },
    tags: ['AI', 'Raspberry Pi', 'Multimodal'], includedComponents: ['AI learning platform', 'Input devices', 'Project hardware'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Introduces practical AI experimentation', 'Connects software intelligence with hardware'], highlightedProjects: ['Multimodal interaction', 'Intelligent devices', 'AI-assisted hardware'],
  },
  {
    id: 'sunfounder-picrawler-ai-robot-kit',
    name: 'SunFounder PiCrawler AI Robot Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'ai-vision', featured: false,
    shortDescription: 'A mobile AI robotics platform for experimenting with movement, perception, and intelligent behavior.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an AI mobile robot' },
    tags: ['AI', 'Robotics', 'Raspberry Pi'], includedComponents: ['Mobile robot platform', 'Vision hardware', 'Motion system'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Combines AI and mobile robotics', 'Supports perception-driven behavior'], highlightedProjects: ['Visual navigation', 'Object response', 'Intelligent movement'],
  },
  {
    id: 'sunfounder-esp32-camera-pro-kit',
    name: 'SunFounder ESP32 Camera Pro Kit',
    brand: 'SunFounder', category: 'sensors', level: 'Intermediate', platform: 'ESP32', collection: 'ai-vision', featured: false,
    shortDescription: 'A compact camera development platform for computer-vision, connected imaging, and detection experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a camera development kit' },
    tags: ['Computer Vision', 'ESP32', 'Camera'], includedComponents: ['Camera development platform', 'Connected controller', 'Vision project hardware'],
    affiliateLinks: { amazon: affiliatePlaceholders.amazon, sunfounder: affiliatePlaceholders.sunfounderProductRequired },
    sellingPoints: ['Compact vision platform', 'Supports connected camera experiments'], highlightedProjects: ['Object detection', 'Connected imaging', 'Visual monitoring'],
  },
  {
    id: 'elegoo-uno-r3-super-starter-kit',
    name: 'ELEGOO UNO R3 Super Starter Kit',
    brand: 'ELEGOO',
    category: 'starter-kits',
    shortDescription:
      'An Arduino-compatible learning kit with an UNO-style controller, breadboard, common components, modules, and guided lessons for first electronics experiments.',
    image: {
      src: '/product-images/electronics-product.svg',
      alt: 'Illustration of an electronics starter kit with a controller board and components',
    },
    level: 'Beginner',
    platform: 'Arduino',
    featured: false,
    tags: ['Arduino', 'UNO R3', 'Breadboard', 'Starter Kit'],
    includedComponents: ['UNO R3-compatible board', 'Solderless breadboard', 'LED assortment', 'Resistors and capacitors', 'Sensor modules', 'Stepper motor and driver', 'Servo motor', 'Jumper wires'],
    affiliateLinks: {
      amazon: affiliatePlaceholders.amazon,
      sunfounder: affiliatePlaceholders.sunfounder,
      additionalVendors: { ELEGOO: 'AFFILIATE_LINK_ELEGOO' },
    },
  },
  {
    id: 'ifixit-essential-electronics-toolkit',
    name: 'iFixit Essential Electronics Toolkit',
    brand: 'iFixit',
    category: 'tools',
    shortDescription:
      'A compact precision toolkit with a bit driver, common specialty bits, tweezers, and opening tools for enclosures and electronics repair tasks.',
    image: {
      src: '/product-images/electronics-product.svg',
      alt: 'Illustration representing a precision electronics toolkit',
    },
    level: 'Beginner',
    platform: 'Electronics',
    collection: 'miscellaneous',
    featured: false,
    tags: ['Hand Tools', 'Precision Driver', 'Tweezers', 'Repair'],
    includedComponents: ['Precision bit driver', '16 precision bits', 'Angled tweezers', 'Spudger', 'Opening picks', 'Opening tool', 'Suction handle', 'Organized tool case'],
    affiliateLinks: {
      amazon: affiliatePlaceholders.amazon,
      sunfounder: affiliatePlaceholders.sunfounder,
      additionalVendors: { iFixit: 'AFFILIATE_LINK_IFIXIT' },
    },
  },
];

export const productById = new Map(products.map((product) => [product.id, product]));
productById.set('sunfounder-raspberry-pi-pico-ultimate-starter-kit', productById.get('sunfounder-euler-pico-ultimate-kit')!);
productById.set('sunfounder-kepler-pico-w-ultimate-starter-kit', productById.get('sunfounder-kepler-pico-w-ultimate-kit')!);

export function getProductsByCategory(category: ProductCategoryId): Product[] {
  return products.filter((product) => product.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured);
}
