export type ProductLevel = 'Beginner' | 'Intermediate' | 'Advanced';
export const productCollectionIds = ['raspberry-pi-pico', 'arduino', 'robotics', 'ai-vision', 'raspberry-pi', 'miscellaneous'] as const;
export type ProductCollectionId = (typeof productCollectionIds)[number];

export type ProductCategoryId =
  | 'starter-kits'
  | 'raspberry-pi-pico'
  | 'arduino'
  | 'sensors'
  | 'displays'
  | 'motors'
  | 'breadboards'
  | 'tools'
  | 'power'
  | 'accessories';

export interface AffiliateLinks {
  amazon?: string;
  sunfounder?: string;
  additionalVendors?: Record<string, string>;
}

export interface KitComponent {
  name: string;
  description: string;
}

export interface KitProject {
  projectId: string;
  title: string;
  description: string;
  difficulty: ProductLevel;
  estimatedTime?: string;
}

export interface KitSalesProfile {
  recommendation: string;
  audienceSummary: string;
  goodFor: string[];
  components: KitComponent[];
  projects: KitProject[];
  sellingPoints: string[];
  documentationUrl: string;
}

export interface PicoKitProfile {
  comparisonLabel: string;
  sectionTitle: string;
  bestFor: string;
  learningFocus: string;
  projectRange: string;
  verifiedProductInfo: string;
  explanation: string;
  selectedComponents?: string[];
  learningAreas: string[];
  projectIds: string[];
  officialProductUrl: string;
  officialDocumentationUrl: string;
}

export interface Product {
  id: string;
  primaryCollection: ProductCollectionId;
  collections: ProductCollectionId[];
  featuredInCollections?: ProductCollectionId[];
  collectionPriority?: Partial<Record<ProductCollectionId, number>>;
  ctaLabel?: string;
  name: string;
  brand: string;
  category: ProductCategoryId;
  shortDescription: string;
  image: {
    src: string;
    alt: string;
  };
  level: ProductLevel;
  platform: string;
  /** @deprecated Use primaryCollection and collections. */
  collection?: ProductCollectionId;
  /** Internal affiliate-program note. Never render this value publicly. */
  commissionRateNote?: string;
  featured: boolean;
  tags: string[];
  includedComponents: string[];
  affiliateLinks: AffiliateLinks;
  kitSalesProfile?: KitSalesProfile;
  sellingPoints?: string[];
  highlightedProjects?: string[];
  officialProductUrl?: string;
  documentationUrl?: string;
  picoKitProfile?: PicoKitProfile;
}

export interface ProductCategory {
  id: ProductCategoryId;
  name: string;
  description: string;
}

/** Replace these values only with product-specific links generated by the affiliate dashboard. */
export const sunFounderPicoAffiliateUrls = {
  thales: 'https://www.sunfounder.com/collections/pico-w-pico/products/pico-starter-kit?ref=tmbxfubs',
  euler: 'https://www.sunfounder.com/collections/pico-w-pico/products/sunfounder-euler-kit?ref=tmbxfubs',
  kepler: 'https://www.sunfounder.com/collections/pico-w-pico/products/sunfounder-raspberry-pi-pico-w-ultimate-starter-kit?ref=tmbxfubs',
} as const;

/** Product-specific placeholders must be replaced only with verified affiliate-dashboard URLs. */
export const sunFounderAffiliateUrls = {
  beginnersLabArduinoUnoR3: 'https://www.sunfounder.com/collections/arduino-kits-bundles/products/sunfounder-beginners-lab-starter-kit-with-original-arduino-uno-r3?ref=tmbxfubs',
  eliteExplorerArduinoUnoR4Wifi: 'https://www.sunfounder.com/collections/arduino-kits-bundles/products/sunfounder-elite-explorer-kit-with-official-arduino-uno-r4-wifi?ref=tmbxfubs',
  threeInOneArduinoUnoR4Minima: 'https://www.sunfounder.com/collections/arduino-kits-bundles/products/sunfounder-3-in-1-ultimate-starter-kit-with-original-arduino-uno-r4-minima?ref=tmbxfubs',
  piDog: 'https://www.sunfounder.com/products/sunfounder-pidog-ai-robot-dog-kit?_pos=6&_sid=bbb1e0141&_ss=r&ref=tmbxfubs',
  galaxyRvr: 'https://www.sunfounder.com/products/sunfounder-galaxyrvr-mars-rover-kit?_pos=1&_sid=41fe2bf74&_ss=r&ref=tmbxfubs',
  piCarX: 'https://www.sunfounder.com/products/picar-x?_pos=1&_sid=38db31399&_ss=r&ref=tmbxfubs',
  aiFusionLab: 'https://www.sunfounder.com/products/sunfounder-ai-fusion-lab-kit?_pos=1&_sid=872f38ba4&_ss=r&ref=tmbxfubs',
  piCrawler: 'https://www.sunfounder.com/products/picrawler-robot-kit?_pos=1&_sid=3bd548c44&_ss=r&ref=tmbxfubs',
  universalMakerSensorKit: 'https://www.sunfounder.com/products/sunfounder-universal-maker-sensor-kit?_pos=1&_sid=8b21fe556&_ss=r&ref=tmbxfubs',
  esp32UltimateStarterKit: 'https://www.sunfounder.com/products/sunfounder-esp32-ultimate-starter-kit-with-esp32-camera-extension-board-battery?_pos=2&_sid=f1ffbc169&_ss=r&ref=tmbxfubs',
  pironman5: 'https://www.sunfounder.com/products/pironman-5-nvme-m-2-ssd-pcie-mini-pc-case-for-raspberry-pi-5?_pos=1&_sid=e63ca1e8a&_ss=r&ref=tmbxfubs',
  pironman5Max: 'https://www.sunfounder.com/products/pironman-5-max?_pos=1&_sid=54e4a04d5&_ss=r&ref=tmbxfubs',
  esp32CameraPro: 'https://www.sunfounder.com/products/sunfounder-esp32-camera-pro-kit?ref=tmbxfubs',
  raphaelKit: 'https://www.sunfounder.com/products/raphael-kit?_pos=1&_sid=640e6da64&_ss=r&ref=tmbxfubs',
  tenInchTouchscreen: 'https://www.sunfounder.com/products/10inch-touchscreen-for-raspberrypi?_pos=1&_sid=76b4c487e&_ss=r&ref=tmbxfubs',
  piPower5: 'https://www.sunfounder.com/products/sunfounder-raspberry-pi-4-ups-power-supply?_pos=1&_sid=5f2753043&_ss=r&ref=tmbxfubs',
  breadVolt: 'https://www.sunfounder.com/products/sunfounder-breadvolt-breadboard-power-supply-module?_pos=1&_sid=ece415576&_ss=r&ref=tmbxfubs',
  ultimateSensorR4: 'https://www.sunfounder.com/products/sunfounder-ultimate-sensor-kit-with-original-arduino-uno-r4-minima?_pos=1&_sid=65f7f423b&_ss=r&ref=tmbxfubs',
  daVinciKit: 'https://www.sunfounder.com/products/sunfounder-davinci-kit?_pos=1&_sid=6c2b42b45&_ss=r&ref=tmbxfubs',
} as const;

export function isActiveAffiliateLink(url?: string): url is string {
  return typeof url === 'string' && /^https?:\/\//i.test(url) && !url.startsWith('AFFILIATE_LINK_');
}

export function hasActiveAffiliateLinks(links: AffiliateLinks): boolean {
  return [links.amazon, links.sunfounder, ...Object.values(links.additionalVendors ?? {})]
    .some(isActiveAffiliateLink);
}

export function getProductPath(product: Product): string {
  return product.picoKitProfile ? `/products/${product.id}` : `/products/details/${product.id}`;
}

export function getProductCtaLabel(product: Product): string {
  if (product.ctaLabel) return product.ctaLabel;
  const shortName = product.name.split(/\s+[–—-]\s+/).at(-1)?.trim() || product.name;
  return `Get the ${shortName} Kit`;
}

export const productCategories: ProductCategory[] = [
  { id: 'starter-kits', name: 'Starter Kits', description: 'All-in-one component collections for a confident first build.' },
  { id: 'raspberry-pi-pico', name: 'Raspberry Pi Pico', description: 'Boards, kits, and accessories for the Pico platform.' },
  { id: 'arduino', name: 'Arduino', description: 'Arduino-compatible boards, shields, and learning kits.' },
  { id: 'sensors', name: 'Sensors', description: 'Modules for measuring light, motion, temperature, distance, and more.' },
  { id: 'displays', name: 'Displays', description: 'LCD, OLED, LED matrix, and indicator display modules.' },
  { id: 'motors', name: 'Motors', description: 'Motors, drivers, servos, and motion-control accessories.' },
  { id: 'breadboards', name: 'Breadboards', description: 'Solderless prototyping boards, jumper wires, and organizers.' },
  { id: 'tools', name: 'Tools', description: 'Meters, cutters, soldering tools, and practical bench essentials.' },
  { id: 'power', name: 'Power', description: 'Safe project power supplies, battery holders, and regulators.' },
  { id: 'accessories', name: 'Accessories', description: 'Useful cables, cases, connectors, and project extras.' },
];

export const products: Product[] = [
  {
    id: 'sunfounder-thales-pico-starter-kit',
    primaryCollection: 'raspberry-pi-pico', collections: ['raspberry-pi-pico'],
    ctaLabel: 'Get the Thales Kit',
    name: 'Raspberry Pi Pico Starter Kit – Thales',
    brand: 'SunFounder',
    category: 'starter-kits',
    shortDescription:
      'This beginner kit contains the core components used in this project and supports additional Raspberry Pi Pico experiments as you continue through the Engineering Maker Lab learning path.',
    image: {
      src: '/product-images/electronics-product.svg',
      alt: 'Generic Engineering Maker Lab illustration representing an electronics starter kit',
    },
    level: 'Beginner',
    platform: 'Raspberry Pi Pico',
    collection: 'raspberry-pi-pico',
    commissionRateNote: '8 percent',
    featured: true,
    tags: ['Raspberry Pi Pico', 'MicroPython', 'Starter Kit'],
    includedComponents: ['Raspberry Pi Pico', 'Breadboard', 'LEDs', 'Resistors', 'Jumper wires', 'Other parts for later beginner projects'],
    affiliateLinks: {
      sunfounder: sunFounderPicoAffiliateUrls.thales,
    },
    kitSalesProfile: {
      recommendation: 'A practical starting point for learning Raspberry Pi Pico programming and basic electronics. The kit combines a Pico board, breadboard components, input devices, and output devices so beginners can complete several progressively more interesting experiments.',
      audienceSummary: 'Complete beginners, students, parents, homeschool families, and makers',
      goodFor: ['Complete beginners', 'Middle and high school students', 'Parents purchasing a STEM kit', 'Homeschool programs', 'Makers learning MicroPython', 'STEM clubs'],
      components: [
        { name: 'Raspberry Pi Pico', description: 'The programmable controller that reads inputs and controls outputs.' },
        { name: 'Breadboard', description: 'Allows circuits to be assembled without soldering.' },
        { name: 'LEDs', description: 'Provide clear visual output for first circuits.' },
        { name: 'Resistors', description: 'Limit current and help protect components.' },
        { name: 'Push buttons', description: 'Introduce digital input and interactive control.' },
        { name: 'RGB LED', description: 'Combines color channels for controllable light experiments.' },
        { name: 'Buzzer', description: 'Adds sound as a programmable output.' },
        { name: 'Potentiometer', description: 'Introduces adjustable analog input.' },
        { name: 'Sensors', description: 'Let projects respond to changes in their surroundings.' },
        { name: 'Jumper wires', description: 'Connect the Pico and components on the breadboard.' },
      ],
      projects: [
        { projectId: 'blink-led', title: 'Blink an LED', description: 'Control a simple output while learning polarity, resistance, and GPIO.', difficulty: 'Beginner', estimatedTime: '20–30 minutes' },
        { projectId: 'push-button-input', title: 'Read a Push Button', description: 'Use a push button as a digital input to control an LED.', difficulty: 'Beginner' },
        { projectId: 'traffic-light', title: 'Traffic Light', description: 'Sequence three LEDs to model a timed traffic signal.', difficulty: 'Beginner' },
        { projectId: 'reaction-game', title: 'Reaction Game', description: 'Combine lights, timing, and player input in an interactive challenge.', difficulty: 'Beginner' },
        { projectId: 'colorful-light', title: 'Colorful Light', description: 'Mix RGB color channels and explore controllable visual output.', difficulty: 'Beginner' },
      ],
      sellingPoints: ['Designed for complete beginners', 'No soldering required for introductory breadboard projects', 'One kit supports multiple experiments', 'Introduces both programming and electronics', 'Projects progress from simple outputs to interactive systems', 'Official SunFounder documentation is available for supported projects'],
      documentationUrl: 'https://docs.sunfounder.com/projects/thales-kit/en/latest/',
    },
    picoKitProfile: {
      comparisonLabel: 'Thales', sectionTitle: 'Thales: Best Simple Starting Point',
      bestFor: 'Complete beginners and lower-cost entry',
      learningFocus: 'Breadboards, LEDs, buttons, basic sensors, and MicroPython fundamentals',
      projectRange: 'A focused beginner path', verifiedProductInfo: '283 items and 18 projects',
      explanation: 'Suitable for complete beginners who want to learn Pico basics without purchasing the largest kit.',
      selectedComponents: ['Raspberry Pi Pico', 'Breadboard', 'LEDs', 'Resistors', 'Push buttons', 'Sound components', 'Basic sensors', 'Jumper wires'],
      learningAreas: ['Blink an LED', 'Read a push button', 'Control RGB LEDs', 'Build a reaction game', 'Learn basic MicroPython'],
      projectIds: ['blink-led', 'push-button-input', 'colorful-light', 'reaction-game'],
      officialProductUrl: 'https://www.sunfounder.com/products/pico-starter-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/thales-kit/en/latest/',
    },
    documentationUrl: 'https://docs.sunfounder.com/projects/thales-kit/en/latest/',
  },
  {
    id: 'sunfounder-euler-pico-ultimate-kit',
    primaryCollection: 'raspberry-pi-pico', collections: ['raspberry-pi-pico'],
    ctaLabel: 'Get the Euler Kit',
    name: 'Raspberry Pi Pico Ultimate Starter Kit – Euler',
    brand: 'SunFounder',
    category: 'starter-kits',
    shortDescription:
      'A beginner-friendly Raspberry Pi Pico kit with a broad component selection for learning circuits, sensors, displays, and physical computing.',
    image: {
      src: '/product-images/sunfounder-pico-ultimate-starter-kit.svg',
      alt: 'Illustration of a Raspberry Pi Pico starter kit and electronic components',
    },
    level: 'Beginner',
    platform: 'Raspberry Pi Pico',
    collection: 'raspberry-pi-pico',
    featured: true,
    tags: ['Raspberry Pi Pico', 'MicroPython', 'Sensors', 'Displays', 'Starter Kit'],
    includedComponents: ['Raspberry Pi Pico with headers', 'Solderless breadboard', 'LEDs', 'Resistor assortment', 'Jumper wires', 'Additional sensors and output components'],
    affiliateLinks: {
      sunfounder: sunFounderPicoAffiliateUrls.euler,
    },
    sellingPoints: ['Broad Pico learning platform', 'Supports electronics and programming practice'],
    highlightedProjects: ['LED and breadboard experiments', 'Sensor projects', 'Display projects'],
    picoKitProfile: {
      comparisonLabel: 'Euler', sectionTitle: 'Euler: Best for More Components and Projects',
      bestFor: 'Beginners who want a larger component collection and a longer project path',
      learningFocus: 'Displays, sounds, drivers, controllers, sensors, and broader electronics applications',
      projectRange: 'A broad, long-form project path', verifiedProductInfo: '320+ components and 113 projects',
      explanation: 'Appropriate for learners who want a broader component collection and significantly more projects without requiring wireless connectivity.',
      selectedComponents: ['Raspberry Pi Pico', 'Displays', 'Sound components', 'Motor drivers', 'Controllers', 'Sensors'],
      learningAreas: ['Displays', 'Motors and drivers', 'Sound', 'Sensors', 'Controllers', 'Larger multi-component projects'],
      projectIds: ['plant-monitor', 'display-experiments', 'motor-control-projects', 'multi-sensor-systems'],
      officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-euler-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/euler-kit/en/latest/',
    },
    documentationUrl: 'https://docs.sunfounder.com/projects/euler-kit/en/latest/',
  },
  {
    id: 'sunfounder-kepler-pico-w-ultimate-kit',
    primaryCollection: 'raspberry-pi-pico', collections: ['raspberry-pi-pico'],
    ctaLabel: 'Get the Kepler Kit',
    name: 'Raspberry Pi Pico W Ultimate Starter Kit – Kepler',
    brand: 'SunFounder', category: 'starter-kits', level: 'Beginner', platform: 'Raspberry Pi Pico W', collection: 'raspberry-pi-pico', featured: false,
    shortDescription: 'A Pico W learning kit for connected electronics, programming, sensors, and interactive hardware experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Pico W electronics kit' },
    tags: ['Raspberry Pi Pico W', 'MicroPython', 'Starter Kit'],
    includedComponents: ['Pico W learning platform', 'Breadboard components', 'Input and output devices'],
    affiliateLinks: { sunfounder: sunFounderPicoAffiliateUrls.kepler },
    sellingPoints: ['Adds wireless-capable Pico learning', 'Supports connected and interactive experiments'],
    highlightedProjects: ['Connected electronics', 'Sensor experiments', 'Interactive outputs'],
    picoKitProfile: {
      comparisonLabel: 'Kepler', sectionTitle: 'Kepler: Best for Wireless and IoT',
      bestFor: 'Beginners who want wireless, IoT, and a larger project library',
      learningFocus: 'Sensors, displays, motors, wireless control, and IoT',
      projectRange: 'The largest Pico project library in this comparison', verifiedProductInfo: '450+ components and 117 projects',
      explanation: 'Uses the Raspberry Pi Pico W and suits visitors interested in wireless control, web-connected projects, and IoT.',
      selectedComponents: ['Raspberry Pi Pico W', 'Sensors', 'Displays', 'Motors', 'Pumps', 'Wireless project hardware'],
      learningAreas: ['Wi-Fi', 'IoT', 'Wireless control', 'Sensors', 'Displays', 'Motors and pumps'],
      projectIds: ['digital-bubble-level', 'wireless-control-experiments', 'iot-sensor-monitoring', 'automated-motor-pump-projects'],
      officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-raspberry-pi-pico-w-ultimate-starter-kit',
      officialDocumentationUrl: 'https://docs.sunfounder.com/projects/kepler-kit/en/latest/',
    },
    documentationUrl: 'https://docs.sunfounder.com/projects/kepler-kit/en/latest/',
  },
  {
    id: 'sunfounder-beginners-lab-arduino-uno-r3',
    primaryCollection: 'arduino', collections: ['arduino'],
    ctaLabel: "Get the Beginner's Lab Kit",
    name: "SunFounder Beginner's Lab Starter Kit with Arduino Uno R3",
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R3', collection: 'arduino', featured: true,
    shortDescription: 'A beginner-oriented Arduino kit for learning circuits, inputs, outputs, and embedded programming.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an Arduino learning kit' },
    tags: ['Arduino', 'Uno R3', 'Starter Kit'], includedComponents: ['Arduino learning platform', 'Breadboard components', 'Sensors and outputs'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.beginnersLabArduinoUnoR3 },
    sellingPoints: ['Beginner-oriented Arduino platform', 'Combines code with hands-on circuits'], highlightedProjects: ['LED control', 'Sensor input', 'Automation experiments'],
    documentationUrl: 'https://docs.sunfounder.com/projects/beginners-lab-kit/en/latest/',
  },
  {
    id: 'sunfounder-elite-explorer-arduino-uno-r4-wifi',
    primaryCollection: 'arduino', collections: ['arduino'],
    ctaLabel: 'Get the Elite Explorer Kit',
    name: 'SunFounder Elite Explorer Kit with Arduino Uno R4 WiFi',
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R4 WiFi', collection: 'arduino', featured: false,
    shortDescription: 'An Arduino Uno R4 WiFi kit for embedded control, connected experiments, and progressively more capable projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a connected Arduino kit' },
    tags: ['Arduino', 'Uno R4 WiFi', 'Embedded Control'], includedComponents: ['Arduino learning platform', 'Prototyping components', 'Input and output devices'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.eliteExplorerArduinoUnoR4Wifi },
    sellingPoints: ['Modern Arduino platform', 'Supports connected control projects'], highlightedProjects: ['Embedded control', 'Connected sensors', 'Interactive devices'],
    documentationUrl: 'https://docs.sunfounder.com/projects/elite-explorer-kit/en/latest/',
  },
  {
    id: 'sunfounder-3-in-1-arduino-uno-r4-minima',
    primaryCollection: 'arduino', collections: ['arduino'],
    ctaLabel: 'Get the 3 in 1 Kit',
    name: 'SunFounder 3 in 1 Ultimate Starter Kit with Arduino Uno R4 Minima',
    brand: 'SunFounder', category: 'arduino', level: 'Beginner', platform: 'Arduino Uno R4 Minima', collection: 'arduino', featured: false,
    shortDescription: 'A broad Arduino Uno R4 Minima starter platform for electronics, sensor, and control experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an Arduino starter platform' },
    tags: ['Arduino', 'Uno R4 Minima', 'Starter Kit'], includedComponents: ['Arduino learning platform', 'Circuit-building components', 'Sensors and outputs'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.threeInOneArduinoUnoR4Minima },
    sellingPoints: ['Supports varied Arduino experiments', 'Builds embedded-control skills'], highlightedProjects: ['Automation', 'Sensor projects', 'Output control'],
    documentationUrl: 'https://docs.sunfounder.com/projects/3in1-kit-r4/en/latest/',
  },
  {
    id: 'sunfounder-pidog-robot-dog-kit',
    primaryCollection: 'robotics', collections: ['robotics'],
    ctaLabel: 'Get the PiDog Kit',
    name: 'SunFounder PiDog Robot Dog Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'robotics', featured: false,
    shortDescription: 'A programmable quadruped platform for exploring coordinated motion, sensing, and higher-level robot behaviors.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a quadruped robot' },
    tags: ['Robotics', 'Raspberry Pi', 'Quadruped'], includedComponents: ['Quadruped robot platform', 'Motion hardware', 'Sensors'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.piDog },
    sellingPoints: ['Explores coordinated robotic motion', 'Supports behavior programming'], highlightedProjects: ['Walking sequences', 'Responsive behaviors', 'Robot interaction'],
    documentationUrl: 'https://docs.sunfounder.com/projects/pidog/en/latest/',
  },
  {
    id: 'sunfounder-galaxyrvr-mars-rover-kit',
    primaryCollection: 'robotics', collections: ['robotics'],
    ctaLabel: 'Get the GalaxyRVR Kit',
    name: 'SunFounder GalaxyRVR Mars Rover Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Arduino', collection: 'robotics', featured: false,
    shortDescription: 'A rover-style robotics platform for navigation, sensing, and programmable mobile-system experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a rover robot' },
    tags: ['Robotics', 'Rover', 'Navigation'], includedComponents: ['Rover platform', 'Drive system', 'Sensors'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.galaxyRvr },
    sellingPoints: ['Rover-focused mobile robotics', 'Combines navigation and sensing'], highlightedProjects: ['Rover navigation', 'Obstacle response', 'Remote control'],
    documentationUrl: 'https://docs.sunfounder.com/projects/galaxy-rvr/en/latest/',
  },
  {
    id: 'sunfounder-picar-x',
    primaryCollection: 'robotics', collections: ['robotics', 'raspberry-pi'],
    ctaLabel: 'Get the PiCar-X Kit',
    name: 'SunFounder PiCar-X',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'robotics', featured: false,
    shortDescription: 'A Raspberry Pi robot car platform for programmable movement, sensing, and vision-assisted experiments.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi robot car' },
    tags: ['Robotics', 'Raspberry Pi', 'Vision'], includedComponents: ['Robot car platform', 'Drive and steering hardware', 'Sensors'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.piCarX },
    sellingPoints: ['Raspberry Pi robotics platform', 'Supports sensing and vision exploration'], highlightedProjects: ['Robot driving', 'Sensor response', 'Vision-assisted behavior'],
    documentationUrl: 'https://docs.sunfounder.com/projects/picar-x-v20/en/latest/',
  },
  {
    id: 'sunfounder-ai-fusion-lab-kit',
    primaryCollection: 'ai-vision', collections: ['ai-vision', 'raspberry-pi'],
    ctaLabel: 'Get the AI Fusion Lab Kit',
    name: 'SunFounder AI Fusion Lab Kit',
    brand: 'SunFounder', category: 'sensors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'ai-vision', featured: true,
    shortDescription: 'An AI learning platform for experimenting with intelligent inputs, multimodal workflows, and Raspberry Pi projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an AI experiment platform' },
    tags: ['AI', 'Raspberry Pi', 'Multimodal'], includedComponents: ['AI learning platform', 'Input devices', 'Project hardware'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.aiFusionLab },
    sellingPoints: ['Introduces practical AI experimentation', 'Connects software intelligence with hardware'], highlightedProjects: ['Multimodal interaction', 'Intelligent devices', 'AI-assisted hardware'],
    documentationUrl: 'https://docs.sunfounder.com/projects/ai-lab-kit/en/latest/',
  },
  {
    id: 'sunfounder-picrawler-ai-robot-kit',
    primaryCollection: 'ai-vision', collections: ['ai-vision'],
    ctaLabel: 'Get the PiCrawler Kit',
    name: 'SunFounder PiCrawler AI Robot Kit',
    brand: 'SunFounder', category: 'motors', level: 'Intermediate', platform: 'Raspberry Pi', collection: 'ai-vision', featured: false,
    shortDescription: 'A mobile AI robotics platform for experimenting with movement, perception, and intelligent behavior.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an AI mobile robot' },
    tags: ['AI', 'Robotics', 'Raspberry Pi'], includedComponents: ['Mobile robot platform', 'Vision hardware', 'Motion system'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.piCrawler },
    sellingPoints: ['Combines AI and mobile robotics', 'Supports perception-driven behavior'], highlightedProjects: ['Visual navigation', 'Object response', 'Intelligent movement'],
    documentationUrl: 'https://docs.sunfounder.com/projects/pi-crawler/en/latest/',
  },
  {
    id: 'sunfounder-universal-maker-sensor-kit',
    primaryCollection: 'miscellaneous', collections: ['miscellaneous', 'arduino', 'raspberry-pi', 'raspberry-pi-pico', 'robotics'],
    ctaLabel: 'Get the Universal Maker Sensor Kit',
    name: 'SunFounder Universal Maker Sensor Kit',
    brand: 'SunFounder', category: 'sensors', level: 'Beginner', platform: 'Arduino, Raspberry Pi, Pico W, and ESP32', collection: 'miscellaneous', featured: false,
    shortDescription: 'A multi-platform collection of sensors, actuators, and displays for learning physical computing across Arduino, Raspberry Pi, Pico W, and ESP32.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a multi-platform sensor and actuator kit' },
    tags: ['Sensors', 'Arduino', 'Raspberry Pi', 'Pico W', 'ESP32'],
    includedComponents: ['Sensor modules', 'Actuators', 'Display modules', 'Multi-platform learning hardware'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.universalMakerSensorKit },
    sellingPoints: ['Supports several popular maker platforms', 'Combines sensing, output, and display experiments', 'Includes official platform-specific learning paths'],
    highlightedProjects: ['Environmental sensing', 'Interactive controls', 'Automation experiments', 'Sensor-guided robotics'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-universal-maker-sensor-kit',
    documentationUrl: 'https://docs.sunfounder.com/projects/umsk/en/latest/',
  },
  {
    id: 'sunfounder-esp32-ultimate-starter-kit',
    primaryCollection: 'miscellaneous', collections: ['miscellaneous', 'robotics', 'ai-vision'],
    ctaLabel: 'Get the ESP32 Ultimate Starter Kit',
    name: 'SunFounder ESP32 Ultimate Starter Kit with ESP32 Board, RoHS Compliant',
    brand: 'SunFounder', category: 'starter-kits', level: 'Beginner', platform: 'ESP32', collection: 'miscellaneous', featured: false,
    shortDescription: 'An ESP32 learning kit for connected electronics, camera experiments, automation, and interactive projects using C++, MicroPython, or Scratch.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an ESP32 electronics and camera kit' },
    tags: ['ESP32', 'IoT', 'Camera', 'Automation'],
    includedComponents: ['ESP32 development board', 'Camera extension board', 'Electronics prototyping components'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.esp32UltimateStarterKit },
    sellingPoints: ['Supports connected and camera-based experiments', 'Offers several programming-language learning paths', 'Combines electronics and IoT projects'],
    highlightedProjects: ['Camera web server', 'Connected weather display', 'Bluetooth-controlled lighting', 'Home automation experiments'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-esp32-ultimate-starter-kit-with-esp32-camera-extension-board-battery?_pos=1&_sid=842afaf70&_ss=r',
    documentationUrl: 'https://docs.sunfounder.com/projects/esp32-starter-kit/en/latest/',
  },
  {
    id: 'sunfounder-pironman-5',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi', 'ai-vision', 'miscellaneous'],
    ctaLabel: 'Get the Pironman 5',
    name: 'SunFounder Pironman 5 NVMe Mini PC Case',
    brand: 'SunFounder', category: 'accessories', level: 'Intermediate', platform: 'Raspberry Pi 5', featured: false,
    shortDescription: 'A Raspberry Pi 5 enclosure for building a compact desktop, home server, or edge-computing system with integrated storage expansion and cooling.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi mini PC enclosure' },
    tags: ['Raspberry Pi 5', 'NVMe', 'Mini PC', 'Cooling'],
    includedComponents: ['Mini PC enclosure', 'NVMe expansion hardware', 'Cooling hardware', 'Status display'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.pironman5 },
    sellingPoints: ['Combines enclosure, storage expansion, and cooling', 'Supports compact Raspberry Pi 5 systems'],
    highlightedProjects: ['Desktop computer', 'Home server', 'Edge-computing system'],
    officialProductUrl: 'https://www.sunfounder.com/products/pironman-5-nvme-m-2-ssd-pcie-mini-pc-case-for-raspberry-pi-5',
    documentationUrl: 'https://docs.sunfounder.com/projects/pironman5/en/latest/pironman5/intro_pironman5.html',
  },
  {
    id: 'sunfounder-pironman-5-max',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi', 'ai-vision', 'miscellaneous'],
    ctaLabel: 'Get the Pironman 5 MAX',
    name: 'SunFounder Pironman 5 MAX',
    brand: 'SunFounder', category: 'accessories', level: 'Advanced', platform: 'Raspberry Pi 5', featured: false,
    shortDescription: 'An expanded Raspberry Pi 5 mini PC enclosure for storage-heavy, AI-assisted, and home-lab builds that need flexible internal expansion.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an expandable Raspberry Pi mini PC enclosure' },
    tags: ['Raspberry Pi 5', 'NVMe', 'AI', 'Home Lab'],
    includedComponents: ['MAX enclosure', 'Storage expansion hardware', 'Cooling hardware', 'Status display'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.pironman5Max },
    sellingPoints: ['Designed for expandable Raspberry Pi 5 systems', 'Supports storage and accelerator-oriented builds'],
    highlightedProjects: ['Network storage', 'AI edge system', 'Home-lab server'],
    officialProductUrl: 'https://www.sunfounder.com/products/pironman-5-max',
    documentationUrl: 'https://docs.sunfounder.com/projects/pironman5/en/latest/pironman5_max/intro_pironman5_max.html',
  },
  {
    id: 'sunfounder-esp32-camera-pro-kit',
    primaryCollection: 'ai-vision', collections: ['ai-vision', 'miscellaneous'],
    ctaLabel: 'Get the ESP32 Camera Pro Kit',
    name: 'SunFounder ESP32 Camera Pro Kit',
    brand: 'SunFounder', category: 'starter-kits', level: 'Intermediate', platform: 'ESP32', featured: false,
    shortDescription: 'An ESP32 camera development kit for learning embedded imaging, wireless monitoring, and compact vision-enabled device workflows.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an ESP32 camera development kit' },
    tags: ['ESP32', 'Camera', 'Wi-Fi', 'Embedded Vision'],
    includedComponents: ['ESP32 camera platform', 'Camera extension hardware', 'Portable power hardware', 'Prototyping accessories'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.esp32CameraPro },
    sellingPoints: ['Combines an ESP32 platform with camera development hardware', 'Supports wireless image and monitoring projects'],
    highlightedProjects: ['Camera web server', 'Remote monitoring', 'Embedded image capture'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-esp32-camera-pro-kit',
    documentationUrl: 'https://docs.sunfounder.com/projects/esp-cam-kit/en/latest/',
  },
  {
    id: 'sunfounder-raphael-raspberry-pi-ultimate-kit',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi'],
    ctaLabel: 'Get the Raphael Kit',
    name: 'SunFounder Raphael Ultimate Starter Kit for Raspberry Pi',
    brand: 'SunFounder', category: 'starter-kits', level: 'Beginner', platform: 'Raspberry Pi', featured: false,
    shortDescription: 'A Raspberry Pi learning kit for progressing from breadboard circuits and GPIO control to sensors, displays, motors, and interactive hardware.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi electronics learning kit' },
    tags: ['Raspberry Pi', 'GPIO', 'Python', 'Starter Kit'],
    includedComponents: ['Breadboard components', 'Sensors', 'Displays', 'Motors and output devices'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.raphaelKit },
    sellingPoints: ['Covers core Raspberry Pi physical-computing skills', 'Supports a broad progression of hardware experiments'],
    highlightedProjects: ['GPIO circuits', 'Sensor experiments', 'Interactive devices'],
    officialProductUrl: 'https://www.sunfounder.com/products/raphael-kit',
    documentationUrl: 'https://docs.sunfounder.com/projects/raphael-kit/en/latest/',
  },
  {
    id: 'sunfounder-10-1-inch-raspberry-pi-touchscreen',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi', 'miscellaneous'],
    ctaLabel: 'Get the 10.1-inch Touchscreen',
    name: 'SunFounder 10.1-inch Raspberry Pi Touchscreen DIY Monitor',
    brand: 'SunFounder', category: 'displays', level: 'Beginner', platform: 'Raspberry Pi', featured: false,
    shortDescription: 'A capacitive touchscreen display for Raspberry Pi dashboards, portable interfaces, control panels, and other visual maker projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi touchscreen monitor' },
    tags: ['Raspberry Pi', 'Touchscreen', 'Display', 'Dashboard'],
    includedComponents: ['10.1-inch display', 'Capacitive touch interface', 'Display controller', 'Mounting hardware'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.tenInchTouchscreen },
    sellingPoints: ['Adds a touch interface to Raspberry Pi projects', 'Suitable for dashboards and compact control panels'],
    highlightedProjects: ['Home dashboard', 'Touch control panel', 'Portable display'],
    officialProductUrl: 'https://www.sunfounder.com/products/10inch-touchscreen-for-raspberrypi',
    documentationUrl: 'https://docs.sunfounder.com/projects/ts10-pro/en/latest/',
  },
  {
    id: 'sunfounder-pipower-5-ups',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi', 'miscellaneous'],
    ctaLabel: 'Get the PiPower 5',
    name: 'SunFounder PiPower 5 UPS Power Supply',
    brand: 'SunFounder', category: 'power', level: 'Intermediate', platform: 'Raspberry Pi and maker boards', featured: false,
    shortDescription: 'A managed UPS power platform for Raspberry Pi and compatible maker boards, with battery backup, monitoring, and safe-shutdown support.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a managed UPS power supply' },
    tags: ['Raspberry Pi', 'UPS', 'Power Management', 'Battery Backup'],
    includedComponents: ['UPS power board', 'Battery backup hardware', 'Power-management controller', 'Monitoring interfaces'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.piPower5 },
    sellingPoints: ['Provides managed backup power for maker systems', 'Supports monitoring and orderly shutdown workflows'],
    highlightedProjects: ['Protected home server', 'Resilient control system', 'Portable maker platform'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-raspberry-pi-4-ups-power-supply',
    documentationUrl: 'https://docs.sunfounder.com/projects/pipower5/en/latest/',
  },
  {
    id: 'sunfounder-breadvolt-power-supply',
    primaryCollection: 'miscellaneous', collections: ['miscellaneous', 'arduino', 'raspberry-pi-pico', 'raspberry-pi', 'robotics'],
    ctaLabel: 'Get the BreadVolt Module',
    name: 'SunFounder BreadVolt Breadboard Power Supply Module',
    brand: 'SunFounder', category: 'power', level: 'Beginner', platform: 'Arduino, Raspberry Pi, Pico, and ESP32', featured: false,
    shortDescription: 'A compact breadboard power module for supplying and monitoring prototype circuits across common microcontroller and single-board-computer projects.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a breadboard power supply module' },
    tags: ['Breadboard', 'Power Supply', 'Prototyping', 'Multi-platform'],
    includedComponents: ['Breadboard power module', 'Power input interfaces', 'Voltage controls', 'Status display'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.breadVolt },
    sellingPoints: ['Provides reusable power control for breadboard projects', 'Works across several maker platforms'],
    highlightedProjects: ['Breadboard prototyping', 'Sensor testing', 'Portable circuit experiments'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-breadvolt-breadboard-power-supply-module',
    documentationUrl: 'https://docs.sunfounder.com/projects/breadvolt/en/latest/',
  },
  {
    id: 'sunfounder-ultimate-sensor-kit-arduino-uno-r4-minima',
    primaryCollection: 'arduino', collections: ['arduino', 'miscellaneous'],
    ctaLabel: 'Get the Ultimate Sensor Kit',
    name: 'SunFounder Ultimate Sensor Kit with Arduino Uno R4 Minima',
    brand: 'SunFounder', category: 'sensors', level: 'Beginner', platform: 'Arduino Uno R4 Minima', featured: false,
    shortDescription: 'An Arduino Uno R4 Minima sensor kit for learning environmental inputs, interactive controls, data display, and connected-device fundamentals.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing an Arduino sensor learning kit' },
    tags: ['Arduino', 'Uno R4 Minima', 'Sensors', 'Physical Computing'],
    includedComponents: ['Arduino Uno R4 Minima', 'Sensor modules', 'Output modules', 'Prototyping hardware'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.ultimateSensorR4 },
    sellingPoints: ['Pairs an official Arduino platform with varied sensor modules', 'Supports hands-on input and output experiments'],
    highlightedProjects: ['Environmental monitor', 'Interactive alarm', 'Sensor data display'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-ultimate-sensor-kit-with-original-arduino-uno-r4-minima',
    documentationUrl: 'https://docs.sunfounder.com/projects/ultimate-sensor-kit/en/latest/',
  },
  {
    id: 'sunfounder-da-vinci-raspberry-pi-starter-kit',
    primaryCollection: 'raspberry-pi', collections: ['raspberry-pi'],
    ctaLabel: 'Get the Da Vinci Kit',
    name: 'SunFounder Da Vinci Starter Kit for Raspberry Pi',
    brand: 'SunFounder', category: 'starter-kits', level: 'Beginner', platform: 'Raspberry Pi', featured: false,
    shortDescription: 'A Raspberry Pi starter kit for learning GPIO programming, breadboard electronics, sensor input, and practical output control.',
    image: { src: '/product-images/electronics-product.svg', alt: 'Generic Engineering Maker Lab illustration representing a Raspberry Pi starter kit' },
    tags: ['Raspberry Pi', 'GPIO', 'Python', 'Electronics'],
    includedComponents: ['Breadboard components', 'Sensors', 'Input devices', 'Output devices'],
    affiliateLinks: { sunfounder: sunFounderAffiliateUrls.daVinciKit },
    sellingPoints: ['Introduces Raspberry Pi programming through physical circuits', 'Supports a structured range of beginner experiments'],
    highlightedProjects: ['LED circuits', 'Sensor input', 'Motor and display control'],
    officialProductUrl: 'https://www.sunfounder.com/products/sunfounder-davinci-kit',
    documentationUrl: 'https://docs.sunfounder.com/projects/davinci-kit/en/latest/',
  },
];

export const productById = new Map(products.map((product) => [product.id, product]));
productById.set('sunfounder-raspberry-pi-pico-ultimate-starter-kit', productById.get('sunfounder-euler-pico-ultimate-kit')!);
productById.set('sunfounder-kepler-pico-w-ultimate-starter-kit', productById.get('sunfounder-kepler-pico-w-ultimate-kit')!);

export function getProductsByCategory(category: ProductCategoryId): Product[] {
  return products.filter((product) => product.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured);
}

export function getProductsByCollection(collectionId: ProductCollectionId): Product[] {
  return products
    .filter((product) => product.collections.includes(collectionId))
    .sort((a, b) => (a.collectionPriority?.[collectionId] ?? 999) - (b.collectionPriority?.[collectionId] ?? 999));
}
